[pytest]
pythonpath = . backend
testpaths = backend/src/tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session

env =
    CORS_ORIGINS=["http://localhost:3000"]
    POSTGRES_USER=test
    POSTGRES_PASSWORD=test
    POSTGRES_HOST=localhost
    PGPORT=5432
    POSTGRES_DB=test


